name: .NET Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - integration

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'TimeResourceManagementAPI.sln'
  TEST_PROJECT: 'test/BusinessLogic.Tests/BusinessLogic.Tests.csproj'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet: ['8.0.x']
        test-type: [unit, integration]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
      
    - name: Run Unit Tests
      if: matrix.test-type == 'unit'
      run: |
        echo "Running Unit Tests..."
        dotnet test ${{ env.TEST_PROJECT }} \
          --configuration Release \
          --no-build \
          --filter "Category=Unit" \
          --verbosity normal \
          --logger "trx;LogFileName=unit-tests.trx" \
          --results-directory ./TestResults
          
    - name: Run Integration Tests
      if: matrix.test-type == 'integration'
      run: |
        echo "Running Integration Tests..."
        dotnet test ${{ env.TEST_PROJECT }} \
          --configuration Release \
          --no-build \
          --filter "Category=Integration" \
          --verbosity normal \
          --logger "trx;LogFileName=integration-tests.trx" \
          --results-directory ./TestResults
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.test-type }}
        path: ./TestResults/
        retention-days: 30
        
    - name: Test Coverage
      run: |
        dotnet test ${{ env.TEST_PROJECT }} \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --settings coverlet.runsettings
          
  test-coverage:
    runs-on: ubuntu-latest
    needs: run-tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Generate Coverage Report
      run: |
        dotnet test ${{ env.TEST_PROJECT }} \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults
          
        reportgenerator \
          -reports:"./TestResults/**/coverage.cobertura.xml" \
          -targetdir:"./CoverageReport" \
          -reporttypes:"Html;Badges"
          
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./CoverageReport/
        
    - name: Coverage Badge
      uses: simplabs/github-action-coverage-badge@v1
      with:
        coverage_file: ./TestResults/**/coverage.cobertura.xml