// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211131519_TimeMigraton")]
    partial class TimeMigraton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCDA34A321C");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GoalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("GoalId")
                        .HasName("PK__Goals__8A4FFF31510AB60C");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Domain.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MeetingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizerID");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MeetingId")
                        .HasName("PK__Meetings__E9F9E9AC481FFB96");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "StartDateTime", "EndDateTime" }, "IX_Meetings_DateTime");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Domain.Models.MeetingParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParticipantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<bool?>("Attendance")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("MeetingID");

                    b.Property<string>("ResponseStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ParticipantId")
                        .HasName("PK__MeetingP__7227997E40069F2B");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "MeetingId", "UserId" }, "UC_MeetingParticipant")
                        .IsUnique()
                        .HasFilter("[MeetingID] IS NOT NULL AND [UserID] IS NOT NULL");

                    b.ToTable("MeetingParticipants");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectManagerID");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABED0D20A58C2");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResourceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<int?>("Availability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<decimal?>("CostPerHour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceId")
                        .HasName("PK__Resource__4ED1814F3DEA3B39");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Domain.Models.ResourceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("HoursUsed")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int")
                        .HasColumnName("ResourceID");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Assigned");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Resource__32499E5721E123D0");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "ResourceId" }, "IX_ResourceAssignments_Resource");

                    b.HasIndex(new[] { "TaskId" }, "IX_ResourceAssignments_Task");

                    b.ToTable("ResourceAssignments");
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA091E7944D1A2F");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Domain.Models.TimeEntry", b =>
                {
                    b.Property<int>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TimeEntryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeEntryId"));

                    b.Property<bool?>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("Billable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TimeEntryId")
                        .HasName("PK__TimeEntr__36FCE7E951552FBD");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "UserId", "EntryDate" }, "IX_TimeEntries_UserDate");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC28179AB0");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Users_Department");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534A262626A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.UserSkill", b =>
                {
                    b.Property<int>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserSkillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSkillId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("UserSkillId")
                        .HasName("PK__UserSkil__2F28BFB6FD29AA02");

                    b.HasIndex("SkillId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserSkills_User");

                    b.HasIndex(new[] { "UserId", "SkillId" }, "UC_UserSkill")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [SkillID] IS NOT NULL");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Domain.Models.UserTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId")
                        .HasName("PK__UserTask__7C6949D1EE7F8366");

                    b.HasIndex(new[] { "AssignedTo" }, "IX_UserTasks_AssignedTo");

                    b.HasIndex(new[] { "ProjectId" }, "IX_UserTasks_Project");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Domain.Models.Department", b =>
                {
                    b.HasOne("Domain.Models.User", "Manager")
                        .WithMany("Departments")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Departments_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.Models.Goal", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Goals_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Meeting", b =>
                {
                    b.HasOne("Domain.Models.User", "Organizer")
                        .WithMany("Meetings")
                        .HasForeignKey("OrganizerId")
                        .HasConstraintName("FK_Meetings_Users");

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Meetings_Projects");

                    b.Navigation("Organizer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.MeetingParticipant", b =>
                {
                    b.HasOne("Domain.Models.Meeting", "Meeting")
                        .WithMany("MeetingParticipants")
                        .HasForeignKey("MeetingId")
                        .HasConstraintName("FK_MeetingParticipants_Meetings");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("MeetingParticipants")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MeetingParticipants_Users");

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.HasOne("Domain.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Projects_Departments");

                    b.HasOne("Domain.Models.User", "ProjectManager")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectManagerId")
                        .HasConstraintName("FK_Projects_Manager");

                    b.Navigation("Department");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("Domain.Models.Resource", b =>
                {
                    b.HasOne("Domain.Models.Department", "Department")
                        .WithMany("Resources")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Resources_Departments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Models.ResourceAssignment", b =>
                {
                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_ResourceAssignments_Projects");

                    b.HasOne("Domain.Models.Resource", "Resource")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("ResourceId")
                        .HasConstraintName("FK_ResourceAssignments_Resources");

                    b.HasOne("Domain.Models.UserTask", "Task")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_ResourceAssignments_UserTasks");

                    b.Navigation("Project");

                    b.Navigation("Resource");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Domain.Models.TimeEntry", b =>
                {
                    b.HasOne("Domain.Models.UserTask", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_TimeEntries_UserTasks");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_TimeEntries_Users");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.HasOne("Domain.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Users_Departments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Models.UserSkill", b =>
                {
                    b.HasOne("Domain.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .HasConstraintName("FK_UserSkills_Skills");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserSkills_Users");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.UserTask", b =>
                {
                    b.HasOne("Domain.Models.User", "AssignedToNavigation")
                        .WithMany("UserTasks")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK_UserTasks_Users");

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("UserTasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_UserTasks_Projects");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Department", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Models.Meeting", b =>
                {
                    b.Navigation("MeetingParticipants");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("ResourceAssignments");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("Domain.Models.Resource", b =>
                {
                    b.Navigation("ResourceAssignments");
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Goals");

                    b.Navigation("MeetingParticipants");

                    b.Navigation("Meetings");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");

                    b.Navigation("UserSkills");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("Domain.Models.UserTask", b =>
                {
                    b.Navigation("ResourceAssignments");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
